// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHCm-LQuvJ4o3W1JgHY5rCwRnZyVnrJzM',
    appId: '1:135943003103:web:9688264b319fa9ff7d426a',
    messagingSenderId: '135943003103',
    projectId: 'trendhub-5b2d5',
    authDomain: 'trendhub-5b2d5.firebaseapp.com',
    storageBucket: 'trendhub-5b2d5.firebasestorage.app',
    measurementId: 'G-ZPRV0MDS75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWQVT4y51OS33Ap_Sgfrvk7kb_3IyxmjQ',
    appId: '1:135943003103:android:b09468185b7f00a77d426a',
    messagingSenderId: '135943003103',
    projectId: 'trendhub-5b2d5',
    storageBucket: 'trendhub-5b2d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9KXCH3gKxPC1hL6bVe2FoY7t60Keto1w',
    appId: '1:135943003103:ios:220963196b77afbb7d426a',
    messagingSenderId: '135943003103',
    projectId: 'trendhub-5b2d5',
    storageBucket: 'trendhub-5b2d5.firebasestorage.app',
    iosBundleId: 'com.example.trendhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9KXCH3gKxPC1hL6bVe2FoY7t60Keto1w',
    appId: '1:135943003103:ios:220963196b77afbb7d426a',
    messagingSenderId: '135943003103',
    projectId: 'trendhub-5b2d5',
    storageBucket: 'trendhub-5b2d5.firebasestorage.app',
    iosBundleId: 'com.example.trendhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHCm-LQuvJ4o3W1JgHY5rCwRnZyVnrJzM',
    appId: '1:135943003103:web:0d49b9304c3eb6697d426a',
    messagingSenderId: '135943003103',
    projectId: 'trendhub-5b2d5',
    authDomain: 'trendhub-5b2d5.firebaseapp.com',
    storageBucket: 'trendhub-5b2d5.firebasestorage.app',
    measurementId: 'G-Z1WSJG9MEJ',
  );
}
